#!/bin/bash
# install.sh — claude-mux installer

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_BASE_DIR="$HOME/Claude"
BASE_DIR=""
BIN_DIR=""
INSTALL_LAUNCHAGENT=true
AUTO_GIT_INIT=false
DEFAULT_PERMISSION_MODE="auto"
ALLOW_CROSS_SESSION_CONTROL=false

usage() {
    cat << EOF
install.sh — Install claude-mux

Usage: install.sh [OPTIONS]

Options:
  --base-dir DIR          Root directory for Claude projects (default: ~/Claude)
  --bin-dir DIR           Directory to install claude-mux binary (default: first writable bin in PATH)
  --auto-git-init         Enable git init in project directories without a repo
  --permission-mode MODE  Set Claude's default permission mode per project
                          Valid: default, acceptEdits, plan, auto, dontAsk, bypassPermissions, "" (disabled)
                          (default: auto)
  --cross-session-control Enable sessions to send slash commands to each other (multi-agent)
  --no-launchagent        Skip LaunchAgent installation
  -h, --help              Show this help message

Examples:
  ./install.sh
  ./install.sh --base-dir ~/work/claude
  ./install.sh --bin-dir ~/.local/bin --no-launchagent
  ./install.sh --auto-git-init --permission-mode acceptEdits
EOF
}

# ── Parse args ────────────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
    case "$1" in
        --base-dir)             BASE_DIR="$2"; shift 2 ;;
        --bin-dir)              BIN_DIR="$2"; shift 2 ;;
        --auto-git-init)        AUTO_GIT_INIT=true; shift ;;
        --permission-mode)      DEFAULT_PERMISSION_MODE="$2"; shift 2 ;;
        --cross-session-control) ALLOW_CROSS_SESSION_CONTROL=true; shift ;;
        --no-launchagent)       INSTALL_LAUNCHAGENT=false; shift ;;
        -h|--help)              usage; exit 0 ;;
        *)                      echo "Unknown option: $1" >&2; echo >&2; usage >&2; exit 1 ;;
    esac
done

BASE_DIR="${BASE_DIR:-$DEFAULT_BASE_DIR}"

# ── Find bin dir ──────────────────────────────────────────────────────────────

find_bin_dir() {
    local candidates=("$HOME/bin" "$HOME/.local/bin" "/usr/local/bin" "/opt/homebrew/bin")
    for dir in "${candidates[@]}"; do
        if [[ -d "$dir" && -w "$dir" ]]; then
            echo "$dir"; return
        fi
    done
    IFS=: read -ra path_dirs <<< "$PATH"
    for dir in "${path_dirs[@]}"; do
        if [[ -d "$dir" && -w "$dir" ]]; then
            echo "$dir"; return
        fi
    done
    echo ""
}

if [[ -z "$BIN_DIR" ]]; then
    BIN_DIR="$(find_bin_dir)"
    if [[ -z "$BIN_DIR" ]]; then
        echo "ERROR: No writable bin directory found in PATH." >&2
        echo "Use --bin-dir to specify one (e.g. --bin-dir ~/.local/bin)." >&2
        exit 1
    fi
fi

if [[ ! -d "$BIN_DIR" ]]; then
    echo "Creating $BIN_DIR..."
    mkdir -p "$BIN_DIR"
fi

if [[ ! -w "$BIN_DIR" ]]; then
    echo "ERROR: $BIN_DIR is not writable." >&2
    exit 1
fi

# ── Install binary ────────────────────────────────────────────────────────────

echo "Installing claude-mux to $BIN_DIR/claude-mux..."
cp "$SCRIPT_DIR/claude-mux" "$BIN_DIR/claude-mux"
chmod +x "$BIN_DIR/claude-mux"

# ── Create base dir ───────────────────────────────────────────────────────────

if [[ ! -d "$BASE_DIR" ]]; then
    echo "Creating base directory $BASE_DIR..."
    mkdir -p "$BASE_DIR"
fi

# ── Create config file ────────────────────────────────────────────────────────

CONFIG_FILE="$HOME/.claude-mux-rc"

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "Creating $CONFIG_FILE..."

    # Format booleans and strings for config file
    git_init_line="AUTO_GIT_INIT=${AUTO_GIT_INIT}"
    [[ "$AUTO_GIT_INIT" == "false" ]] && git_init_line="#AUTO_GIT_INIT=false"

    permission_line="DEFAULT_PERMISSION_MODE=\"${DEFAULT_PERMISSION_MODE}\""
    [[ "$DEFAULT_PERMISSION_MODE" == "auto" ]] && permission_line="#DEFAULT_PERMISSION_MODE=\"auto\""

    cross_line="ALLOW_CROSS_SESSION_CONTROL=${ALLOW_CROSS_SESSION_CONTROL}"
    [[ "$ALLOW_CROSS_SESSION_CONTROL" == "false" ]] && cross_line="#ALLOW_CROSS_SESSION_CONTROL=false"

    cat > "$CONFIG_FILE" << CONFIG_EOF
# ~/.claude-mux-rc — claude-mux user configuration
# Generated by install.sh. Uncomment and edit to override defaults.

# Root directory containing category and project directories.
# Default: \$HOME/Claude
BASE_DIR="${BASE_DIR}"

# Run git init and create .gitignore in project directories without a repo.
# Default: false
${git_init_line}

# Set Claude's permissions.defaultMode for each project.
# Valid: "" (disabled), "default", "acceptEdits", "plan", "auto", "dontAsk", "bypassPermissions"
# Default: "auto"
${permission_line}

# Allow sessions to send slash commands to other sessions via tmux.
# Enable for multi-agent orchestration. Default: false
${cross_line}
CONFIG_EOF
else
    echo "Config $CONFIG_FILE already exists — skipping."
fi

# ── Install LaunchAgent ───────────────────────────────────────────────────────

if [[ "$INSTALL_LAUNCHAGENT" == "true" ]]; then
    LAUNCHAGENTS_DIR="$HOME/Library/LaunchAgents"
    PLIST_SRC="$SCRIPT_DIR/com.user.claude-mux.plist"
    PLIST_DEST="$LAUNCHAGENTS_DIR/com.user.claude-mux.plist"

    if [[ ! -f "$PLIST_SRC" ]]; then
        echo "WARNING: com.user.claude-mux.plist not found — skipping LaunchAgent install."
    else
        mkdir -p "$LAUNCHAGENTS_DIR"

        if launchctl list | grep -q "com.user.claude-mux" 2>/dev/null; then
            echo "Unloading existing LaunchAgent..."
            launchctl unload "$PLIST_DEST" 2>/dev/null || true
        fi

        echo "Installing LaunchAgent to $PLIST_DEST..."
        cp "$PLIST_SRC" "$PLIST_DEST"
        launchctl load "$PLIST_DEST"
        echo "LaunchAgent installed and loaded."
    fi
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "claude-mux installed successfully."
echo ""
echo "  Binary:    $BIN_DIR/claude-mux"
echo "  Base dir:  $BASE_DIR"
echo "  Config:    $CONFIG_FILE"
[[ "$INSTALL_LAUNCHAGENT" == "true" ]] && echo "  LaunchAgent: com.user.claude-mux (loaded)"
echo ""
echo "Run 'claude-mux --help' to get started."
